services:
    laravel.test:
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'seediq-laravel/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        networks:
            - sail
        depends_on:
            - redis
        command: /bin/bash -c "
              php artisan optimize:clear && \
              php artisan config:cache && \
              php artisan migrate && \
              php artisan serve --host=0.0.0.0 --port=80
          "
        expose:
            - "80"

    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        expose:
            - "6379"

    laravel.worker:
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'seediq-laravel/worker'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            QUEUE_CONNECTION: '${QUEUE_CONNECTION:-redis}'
            API_SERVICE_HOST: '${API_SERVICE_HOST:-laravel.test}'
            API_SERVICE_PORT: '${API_SERVICE_PORT:-80}'
        networks:
            - sail
        depends_on:
            - redis
        restart: unless-stopped
        command: /bin/bash -lc "php artisan queue:work ${QUEUE_CONNECTION:-redis} --sleep=3 --tries=3 --timeout=90"

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
